name: auth
description: Auth service

version: 1.0.0

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  conduit: ^4.4.0
  conduit_core: ^4.4.0
  conduit_postgresql: ^4.4.0
  jaguar_jwt: 3.0.0

# path: ^1.8.0
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
